/**
 * Scans public/assets/fonts and generates src/engine/local-fonts.ts
 *
 *   npm run fonts
 *
 * Naming convention:  FamilyName-Style.ttf   e.g.  Poppins-Bold.ttf
 * Supported extensions: .ttf .otf .woff .woff2
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = path.join(root, 'public', 'assets', 'fonts');
const OUT = path.join(root, 'src', 'engine', 'local-fonts.ts');

const EXTS = new Set(['.ttf', '.otf', '.woff', '.woff2']);

// style token -> [cssWeight, cssStyle]
const STYLES = {
  thin: ['100', 'normal'],
  extralight: ['200', 'normal'],
  ultralight: ['200', 'normal'],
  light: ['300', 'normal'],
  regular: ['400', 'normal'],
  normal: ['400', 'normal'],
  book: ['400', 'normal'],
  medium: ['500', 'normal'],
  semibold: ['600', 'normal'],
  demibold: ['600', 'normal'],
  bold: ['700', 'normal'],
  extrabold: ['800', 'normal'],
  black: ['900', 'normal'],
  heavy: ['900', 'normal'],
  italic: ['400', 'italic'],
  thinitalic: ['100', 'italic'],
  lightitalic: ['300', 'italic'],
  mediumitalic: ['500', 'italic'],
  semibolditalic: ['600', 'italic'],
  bolditalic: ['700', 'italic'],
  extrabolditalic: ['800', 'italic'],
  blackitalic: ['900', 'italic'],
};

function humanize(family) {
  return family
    .replace(/[_]+/g, ' ')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .trim();
}

if (!fs.existsSync(FONT_DIR)) {
  fs.mkdirSync(FONT_DIR, { recursive: true });
}

/** Recurse so you can keep each family in its own subfolder. */
function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (EXTS.has(path.extname(entry.name).toLowerCase())) out.push(full);
  }
  return out;
}

const files = walk(FONT_DIR);

/** family -> faces[] */
const families = new Map();

for (const abs of files) {
  const file = path.relative(FONT_DIR, abs).split(path.sep).join('/');
  const ext = path.extname(abs);
  let stem = path.basename(abs, ext);

  // "Inter-VariableFont_wght" -> treat as Regular
  stem = stem.replace(/[-_]?VariableFont.*$/i, '-Regular');

  // Accept "Family-Style", "Family Style" and plain "Family".
  //   The Seasons Bold.ttf  ->  family "The Seasons", style "Bold"
  //   Lato-Bold.ttf         ->  family "Lato",        style "Bold"
  const STYLE_WORDS =
    /^(thin|extralight|ultralight|light|regular|normal|book|medium|semibold|demibold|bold|extrabold|black|heavy|italic|oblique)$/i;

  let rawFamily;
  let rawStyle = 'Regular';

  if (stem.includes('-')) {
    const i = stem.lastIndexOf('-');
    rawFamily = stem.slice(0, i);
    rawStyle = stem.slice(i + 1) || 'Regular';
  } else {
    // trailing space-separated style words, e.g. "The Seasons Bold Italic"
    const parts = stem.split(/\s+/);
    const tail = [];
    while (parts.length > 1 && STYLE_WORDS.test(parts[parts.length - 1])) {
      tail.unshift(parts.pop());
    }
    rawFamily = parts.join(' ');
    if (tail.length) rawStyle = tail.join('');
  }
  if (!rawFamily) continue;

  const key = rawStyle.toLowerCase().replace(/[^a-z]/g, '').replace('oblique', 'italic');
  const [weight, style] = STYLES[key] ?? ['400', 'normal'];

  const family = humanize(rawFamily);
  if (!families.has(family)) families.set(family, []);
  families.get(family).push({
    src: `/assets/fonts/${file}`,
    weight,
    style,
    label: rawStyle,
  });
}

// de-dup identical weight+style, keep woff2 first
for (const [family, faces] of families) {
  const seen = new Map();
  faces.sort((a, b) => {
    const rank = (s) => (s.src.endsWith('.woff2') ? 0 : s.src.endsWith('.woff') ? 1 : 2);
    return rank(a) - rank(b);
  });
  for (const f of faces) {
    const k = `${f.weight}/${f.style}`;
    if (!seen.has(k)) seen.set(k, f);
  }
  families.set(family, [...seen.values()]);
}

const list = [...families.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([family, faces]) => ({ family, faces }));

const banner = `/**
 * AUTO-GENERATED by scripts/scan-fonts.mjs — do not edit by hand.
 * Add font files to public/assets/fonts then run:  npm run fonts
 *
 * ${list.length} local ${list.length === 1 ? 'family' : 'families'} found.
 */

export interface LocalFontFace {
  src: string;
  weight: string;
  style: string;
  label: string;
}

export interface LocalFontFamily {
  family: string;
  faces: LocalFontFace[];
}

export const LOCAL_FONTS: LocalFontFamily[] = ${JSON.stringify(list, null, 2)};
`;

fs.writeFileSync(OUT, banner);

if (list.length === 0) {
  console.log('No font files found in public/assets/fonts.');
  console.log('Drop some .ttf/.otf/.woff2 files there and run this again.');
} else {
  console.log(`Found ${list.length} font ${list.length === 1 ? 'family' : 'families'}:`);
  for (const { family, faces } of list) {
    console.log(`  ${family.padEnd(24)} ${faces.map((f) => f.label).join(', ')}`);
  }
}
console.log(`\nWrote ${path.relative(root, OUT)}`);
