/**
 * AUTO-GENERATED by scripts/scan-fonts.mjs — do not edit by hand.
 * Add font files to public/assets/fonts then run:  npm run fonts
 *
 * 11 local families found.
 */

export interface LocalFontFace {
  src: string;
  weight: string;
  style: string;
  label: string;
}

export interface LocalFontFamily {
  family: string;
  faces: LocalFontFace[];
}

export const LOCAL_FONTS: LocalFontFamily[] = [
  {
    "family": "Cormorant",
    "faces": [
      {
        "src": "/assets/fonts/Cormorant-Bold.otf",
        "weight": "700",
        "style": "normal",
        "label": "Bold"
      },
      {
        "src": "/assets/fonts/Cormorant-Regular.otf",
        "weight": "400",
        "style": "normal",
        "label": "Regular"
      }
    ]
  },
  {
    "family": "Cormorant Infant",
    "faces": [
      {
        "src": "/assets/fonts/CormorantInfant-Bold.otf",
        "weight": "700",
        "style": "normal",
        "label": "Bold"
      },
      {
        "src": "/assets/fonts/CormorantInfant-Regular.otf",
        "weight": "400",
        "style": "normal",
        "label": "Regular"
      }
    ]
  },
  {
    "family": "Cormorant SC",
    "faces": [
      {
        "src": "/assets/fonts/CormorantSC-Bold.otf",
        "weight": "700",
        "style": "normal",
        "label": "Bold"
      },
      {
        "src": "/assets/fonts/CormorantSC-Regular.otf",
        "weight": "400",
        "style": "normal",
        "label": "Regular"
      }
    ]
  },
  {
    "family": "Cormorant Unicase",
    "faces": [
      {
        "src": "/assets/fonts/CormorantUnicase-Bold.otf",
        "weight": "700",
        "style": "normal",
        "label": "Bold"
      },
      {
        "src": "/assets/fonts/CormorantUnicase-Regular.otf",
        "weight": "400",
        "style": "normal",
        "label": "Regular"
      }
    ]
  },
  {
    "family": "Cormorant Upright",
    "faces": [
      {
        "src": "/assets/fonts/CormorantUpright-Bold.otf",
        "weight": "700",
        "style": "normal",
        "label": "Bold"
      },
      {
        "src": "/assets/fonts/CormorantUpright-Regular.otf",
        "weight": "400",
        "style": "normal",
        "label": "Regular"
      }
    ]
  },
  {
    "family": "Lato",
    "faces": [
      {
        "src": "/assets/fonts/Lato-Bold.ttf",
        "weight": "700",
        "style": "normal",
        "label": "Bold"
      },
      {
        "src": "/assets/fonts/Lato-Regular.ttf",
        "weight": "400",
        "style": "normal",
        "label": "Regular"
      }
    ]
  },
  {
    "family": "Merriweather",
    "faces": [
      {
        "src": "/assets/fonts/Merriweather-Bold.ttf",
        "weight": "700",
        "style": "normal",
        "label": "Bold"
      },
      {
        "src": "/assets/fonts/Merriweather-Regular.ttf",
        "weight": "400",
        "style": "normal",
        "label": "Regular"
      }
    ]
  },
  {
    "family": "Montserrat Alternates",
    "faces": [
      {
        "src": "/assets/fonts/MontserratAlternates-Bold.otf",
        "weight": "700",
        "style": "normal",
        "label": "Bold"
      },
      {
        "src": "/assets/fonts/MontserratAlternates-Regular.otf",
        "weight": "400",
        "style": "normal",
        "label": "Regular"
      }
    ]
  },
  {
    "family": "Playfair Display",
    "faces": [
      {
        "src": "/assets/fonts/PlayfairDisplay-Bold.ttf",
        "weight": "700",
        "style": "normal",
        "label": "Bold"
      },
      {
        "src": "/assets/fonts/PlayfairDisplay-Regular.ttf",
        "weight": "400",
        "style": "normal",
        "label": "Regular"
      }
    ]
  },
  {
    "family": "The Seasons",
    "faces": [
      {
        "src": "/assets/fonts/The Seasons Bold.ttf",
        "weight": "700",
        "style": "normal",
        "label": "Bold"
      },
      {
        "src": "/assets/fonts/The Seasons Italic.ttf",
        "weight": "400",
        "style": "italic",
        "label": "Italic"
      },
      {
        "src": "/assets/fonts/The Seasons Regular.ttf",
        "weight": "400",
        "style": "normal",
        "label": "Regular"
      }
    ]
  },
  {
    "family": "Wintersay",
    "faces": [
      {
        "src": "/assets/fonts/Wintersay.ttf",
        "weight": "400",
        "style": "normal",
        "label": "Regular"
      }
    ]
  }
];
