import fs from 'node:fs';
import path from 'node:path';

let pass = 0;
let fail = 0;
const failures = [];

const check = (name, cond, detail = '') => {
  if (cond) {
    pass++;
    console.log(`PASS ${name}`);
  } else {
    fail++;
    failures.push(`${name}${detail ? ` — ${detail}` : ''}`);
    console.log(`FAIL ${name}${detail ? ` — ${detail}` : ''}`);
  }
};

function walkDir(dir, fileList = []) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat.isDirectory()) {
      walkDir(filePath, fileList);
    } else if (file.endsWith('.ts') || file.endsWith('.tsx') || file.endsWith('.js') || file.endsWith('.mjs')) {
      fileList.push(filePath);
    }
  }
  return fileList;
}

const srcDir = path.resolve('src');
const canvasDir = path.resolve('src/render/canvas');
const allSrcFiles = walkDir(srcDir);

/* ----------------------------- Fabric import boundary (spec 05 §1) -- */

console.log('\n=== Fabric is imported in src/render/canvas/ only ===');
{
  const fabricImportRegex = /(from\s+['"]fabric['"]|import\s+['"]fabric['"]|import\s*\(\s*['"]fabric['"]\s*\))/;
  const offendingImports = [];

  for (const filePath of allSrcFiles) {
    // Built artifacts (*.built.mjs) are generated by esbuild and excluded from source check
    if (filePath.endsWith('.built.mjs')) continue;

    const content = fs.readFileSync(filePath, 'utf-8');
    if (fabricImportRegex.test(content)) {
      const isInsideCanvasDir = filePath.startsWith(canvasDir);
      // Tests in src/render/canvas/ and helper files for tests may import fabric for assertions
      if (!isInsideCanvasDir) {
        offendingImports.push(filePath);
      }
    }
  }

  check(
    'no file outside src/render/canvas/ imports fabric',
    offendingImports.length === 0,
    offendingImports.join(', '),
  );
}

/* ----------------------------- No Fabric types exported outside canvas -- */

console.log('\n=== No file outside src/render/canvas/ exports a Fabric type ===');
{
  const fabricTypes = [
    'Canvas',
    'StaticCanvas',
    'FabricObject',
    'FabricImage',
    'FabricText',
    'Textbox',
    'Rect',
    'Circle',
    'Ellipse',
    'Triangle',
    'Polygon',
    'Line',
    'Group',
    'ActiveSelection',
  ];

  const outsideFiles = allSrcFiles.filter(
    (f) => !f.startsWith(canvasDir) && !f.endsWith('.built.mjs') && !f.endsWith('.test.mjs'),
  );

  const offendingExports = [];
  for (const filePath of outsideFiles) {
    const content = fs.readFileSync(filePath, 'utf-8');
    for (const type of fabricTypes) {
      const exportTypeRegex = new RegExp(`export\\s+(type|interface|class|const|function|var|let)\\s+.*\\b${type}\\b`);
      if (exportTypeRegex.test(content)) {
        offendingExports.push(`${filePath}: exports ${type}`);
      }
    }
  }

  check(
    'no Fabric types exported outside src/render/canvas/',
    offendingExports.length === 0,
    offendingExports.join(', '),
  );
}

/* --------------------------- Invariant: No toJSON / toObject calls in src -- */

console.log('\n=== Invariant: No toJSON() or toObject() calls in src ===');
{
  const bannedMethodsRegex = /\b(canvas|engine|object|target)\.(toJSON|toObject)\s*\(/;
  const offendingCalls = [];

  for (const filePath of allSrcFiles) {
    if (filePath.endsWith('.built.mjs') || filePath.endsWith('.test.mjs')) continue;
    const content = fs.readFileSync(filePath, 'utf-8');
    if (bannedMethodsRegex.test(content)) {
      offendingCalls.push(filePath);
    }
  }

  check(
    'no canvas.toJSON() or toObject() called anywhere in src',
    offendingCalls.length === 0,
    offendingCalls.join(', '),
  );
}

/* ----------------------------- Invariant: No * 72 or / 72 in src/render -- */

console.log('\n=== Invariant: No * 72 or / 72 in src/render ===');
{
  const renderDir = path.resolve('src/render');
  const renderFiles = walkDir(renderDir).filter(
    (f) => !f.endsWith('.built.mjs') && !f.endsWith('.test.mjs'),
  );
  const math72Regex = new RegExp('([*/]\\s*72\\b|\\b72\\s*[*/])');
  const offendingMath = [];

  for (const filePath of renderFiles) {
    const content = fs.readFileSync(filePath, 'utf-8');
    if (math72Regex.test(content)) {
      offendingMath.push(filePath);
    }
  }

  check(
    'no raw * 72 or / 72 in src/render/ (conversions via model/units only)',
    offendingMath.length === 0,
    offendingMath.join(', '),
  );
}

/* --------------------------- React seam: at most 2 useEffect in CanvasHost -- */

console.log('\n=== CanvasHost has at most 2 useEffect hooks ===');
{
  const canvasHostPath = path.resolve('src/render/canvas/CanvasHost.tsx');
  const content = fs.readFileSync(canvasHostPath, 'utf-8');
  const useEffectMatches = content.match(/\buseEffect\s*\(/g) || [];
  check(
    'CanvasHost has at most 2 useEffect hooks',
    useEffectMatches.length <= 2,
    `found ${useEffectMatches.length}`,
  );
}

/* ----------------------------------------------------------------- summary -- */

console.log(`\n${'-'.repeat(48)}`);
if (fail === 0) {
  console.log(`ALL FABRIC BOUNDARY TESTS PASSED (${pass} checks)`);
} else {
  console.log(`${pass} passed, ${fail} FAILED`);
  for (const f of failures) console.log(`  - ${f}`);
  process.exitCode = 1;
}
