import type { ClueWord } from './generator';

/**
 * Built-in themed clue banks.
 *
 * Unlike a word search, a crossword needs a *clue* for every answer, which is
 * the slow part of authoring a book. These ship ready-written so a themed title
 * can be produced without typing anything, and every entry can still be edited
 * on the canvas afterwards.
 *
 * Each bank holds at least 25 pairs so it can feed an expert grid without
 * repeating.
 */

export interface ClueBank {
  id: string;
  name: string;
  audience: 'kids' | 'general' | 'adult';
  words: ClueWord[];
}

const mk = (rows: [string, string][]): ClueWord[] =>
  rows.map(([word, clue]) => ({ word, clue }));

export const CLUE_BANKS: ClueBank[] = [
  {
    id: 'animals',
    name: 'Animals',
    audience: 'kids',
    words: mk([
      ['ELEPHANT', 'Largest land mammal'],
      ['GIRAFFE', 'Tallest animal on earth'],
      ['DOLPHIN', 'Clever sea mammal'],
      ['PENGUIN', 'Flightless bird of the ice'],
      ['TIGER', 'Striped big cat'],
      ['ZEBRA', 'Stripy relative of the horse'],
      ['MONKEY', 'Swinging primate'],
      ['RABBIT', 'Long-eared hopper'],
      ['LEOPARD', 'Spotted big cat'],
      ['OCTOPUS', 'Eight-armed sea creature'],
      ['TORTOISE', 'Slow reptile with a shell'],
      ['CHEETAH', 'Fastest animal on land'],
      ['FLAMINGO', 'Pink wading bird'],
      ['WALRUS', 'Tusked Arctic mammal'],
      ['PANDA', 'Bamboo-eating bear'],
      ['OTTER', 'Playful river swimmer'],
      ['BADGER', 'Striped nocturnal burrower'],
      ['LIZARD', 'Scaly sun-basker'],
      ['CAMEL', 'Humped desert traveller'],
      ['FALCON', 'Swift bird of prey'],
      ['BUFFALO', 'Large wild bovine'],
      ['RACCOON', 'Masked night raider'],
      ['HEDGEHOG', 'Spiny garden visitor'],
      ['SQUIRREL', 'Nut-burying climber'],
      ['KANGAROO', 'Hopping Australian marsupial'],
      ['BEAVER', 'Dam-building rodent'],
    ]),
  },
  {
    id: 'food',
    name: 'Food & cooking',
    audience: 'general',
    words: mk([
      ['CINNAMON', 'Warm baking spice from bark'],
      ['OMELETTE', 'Folded egg dish'],
      ['VANILLA', 'Pod used to flavour ice cream'],
      ['PARSLEY', 'Green garnish herb'],
      ['NOODLE', 'Long strand of pasta'],
      ['BUTTER', 'Churned dairy spread'],
      ['GARLIC', 'Pungent bulb'],
      ['LENTIL', 'Small pulse used in soup'],
      ['PEPPER', 'Ground with salt'],
      ['SIMMER', 'Cook just below boiling'],
      ['KNEAD', 'Work dough by hand'],
      ['WHISK', 'Beat with a wire tool'],
      ['ROAST', 'Cook in a hot oven'],
      ['MARINATE', 'Soak in flavour before cooking'],
      ['SAFFRON', 'Costliest spice of all'],
      ['CHEDDAR', 'Sharp English cheese'],
      ['AVOCADO', 'Green fruit for guacamole'],
      ['BISCUIT', 'Crisp baked snack'],
      ['CUSTARD', 'Sweet yellow sauce'],
      ['GRIDDLE', 'Flat cooking plate'],
      ['SKILLET', 'Heavy frying pan'],
      ['YOGURT', 'Cultured dairy pot'],
      ['ALMOND', 'Nut used in marzipan'],
      ['OREGANO', 'Herb on a pizza'],
      ['MERINGUE', 'Whipped egg white dessert'],
      ['CARAMEL', 'Melted sugar sweet'],
    ]),
  },
  {
    id: 'nature',
    name: 'Nature',
    audience: 'general',
    words: mk([
      ['BLOSSOM', 'Spring flower on a tree'],
      ['GLACIER', 'Slow river of ice'],
      ['MEADOW', 'Field of wild grass'],
      ['CANYON', 'Deep river-cut gorge'],
      ['THUNDER', 'Rumble after lightning'],
      ['ORCHID', 'Exotic flowering plant'],
      ['BOULDER', 'Very large rock'],
      ['ESTUARY', 'Where river meets sea'],
      ['LAGOON', 'Shallow water behind a reef'],
      ['SUMMIT', 'Very top of a mountain'],
      ['WILLOW', 'Weeping riverside tree'],
      ['PEBBLE', 'Small smooth stone'],
      ['RAINBOW', 'Arc of colour after rain'],
      ['FOREST', 'Dense stand of trees'],
      ['MARSH', 'Boggy wetland'],
      ['CAVERN', 'Large underground chamber'],
      ['BREEZE', 'Gentle wind'],
      ['HARVEST', 'Gathering of crops'],
      ['CLOVER', 'Lucky three-leafed plant'],
      ['SUNRISE', 'Start of the day'],
      ['TIMBER', 'Wood ready for building'],
      ['STREAM', 'Small flowing watercourse'],
      ['ACORN', 'Seed of the oak'],
      ['DESERT', 'Very dry region'],
      ['VOLCANO', 'Mountain that erupts'],
      ['LICHEN', 'Crust growing on stone'],
    ]),
  },
  {
    id: 'travel',
    name: 'Travel',
    audience: 'adult',
    words: mk([
      ['PASSPORT', 'Needed to cross a border'],
      ['SUITCASE', 'Packed for a trip'],
      ['TERMINAL', 'Airport building'],
      ['COMPASS', 'Points to the north'],
      ['HARBOUR', 'Sheltered place for boats'],
      ['JOURNEY', 'Trip from one place to another'],
      ['VOYAGE', 'Long sea trip'],
      ['CUSTOMS', 'Checked on arrival'],
      ['RAILWAY', 'Train network'],
      ['SOUVENIR', 'Bought to remember a place'],
      ['LANDMARK', 'Famous sight in a city'],
      ['BACKPACK', 'Carried on the shoulders'],
      ['DEPARTURE', 'Leaving time on the board'],
      ['TRANSIT', 'Passing through'],
      ['CABIN', 'Room on a ship'],
      ['SAFARI', 'Trip to see wild animals'],
      ['HOSTEL', 'Cheap place to stay'],
      ['ITINERARY', 'Plan of the trip'],
      ['SHUTTLE', 'Bus between terminals'],
      ['SEASIDE', 'Coastal holiday spot'],
      ['CARRIAGE', 'Part of a train'],
      ['MARKET', 'Place to browse local stalls'],
      ['VISA', 'Permission to enter'],
      ['ROUTE', 'Way taken to get there'],
      ['SUMMIT', 'Peak reached by climbers'],
      ['ISLAND', 'Land surrounded by sea'],
    ]),
  },
  {
    id: 'home',
    name: 'Around the home',
    audience: 'general',
    words: mk([
      ['CUSHION', 'Soft seat padding'],
      ['CURTAIN', 'Hangs at a window'],
      ['MIRROR', 'Shows your reflection'],
      ['KETTLE', 'Boils water for tea'],
      ['BLANKET', 'Keeps you warm in bed'],
      ['CUPBOARD', 'Storage with a door'],
      ['LADDER', 'Climbed to reach high up'],
      ['CARPET', 'Covers the floor'],
      ['LANTERN', 'Portable light'],
      ['SHELF', 'Holds books on a wall'],
      ['DRAWER', 'Slides out of a chest'],
      ['PILLOW', 'Rests your head'],
      ['TEAPOT', 'Has a spout and a lid'],
      ['GARDEN', 'Outdoor space at home'],
      ['ATTIC', 'Room under the roof'],
      ['HALLWAY', 'Passage inside a house'],
      ['BALCONY', 'Platform off an upper room'],
      ['CHIMNEY', 'Smoke goes up it'],
      ['DOORBELL', 'Rung by a visitor'],
      ['WARDROBE', 'Where clothes hang'],
      ['SOFA', 'Long comfortable seat'],
      ['BASKET', 'Woven carrier'],
      ['CANDLE', 'Burns with a wick'],
      ['MANTEL', 'Shelf above a fireplace'],
      ['STAIRS', 'Climbed between floors'],
      ['PANTRY', 'Small food store'],
    ]),
  },
  {
    id: 'sports',
    name: 'Sports',
    audience: 'general',
    words: mk([
      ['MARATHON', 'Long-distance road race'],
      ['CRICKET', 'Game with bat and wickets'],
      ['REFEREE', 'Official with a whistle'],
      ['STADIUM', 'Big sports venue'],
      ['TROPHY', 'Prize for winning'],
      ['ARCHERY', 'Sport of bow and arrow'],
      ['FENCING', 'Duelling with blades'],
      ['ROWING', 'Propelled by oars'],
      ['SPRINT', 'Very fast short run'],
      ['HURDLE', 'Jumped in a track race'],
      ['GOALIE', 'Guards the net'],
      ['SKIING', 'Downhill on snow'],
      ['SURFING', 'Riding ocean waves'],
      ['PENALTY', 'Awarded for a foul'],
      ['CAPTAIN', 'Leader of a team'],
      ['MEDAL', 'Hung round a winner'],
      ['RELAY', 'Race with a baton'],
      ['BOXING', 'Sport fought in rounds'],
      ['TENNIS', 'Played over a net with rackets'],
      ['DEFENCE', 'Stops the other side scoring'],
      ['COACH', 'Trains the team'],
      ['VICTORY', 'A win'],
      ['CLIMBING', 'Ascending rock faces'],
      ['PITCH', 'Where football is played'],
      ['SCORE', 'Running total of points'],
      ['ATHLETE', 'Competitor in sport'],
    ]),
  },
  {
    id: 'school',
    name: 'School',
    audience: 'kids',
    words: mk([
      ['PENCIL', 'Written with, and rubbed out'],
      ['TEACHER', 'Leads the class'],
      ['LIBRARY', 'Full of books to borrow'],
      ['SCIENCE', 'Subject with experiments'],
      ['HISTORY', 'Subject about the past'],
      ['GEOGRAPHY', 'Subject about maps and places'],
      ['HOMEWORK', 'Done after school'],
      ['SPELLING', 'Putting letters in order'],
      ['PLAYGROUND', 'Where you run at break'],
      ['CLASSROOM', 'Where lessons happen'],
      ['CRAYON', 'Waxy colouring stick'],
      ['SCISSORS', 'Used for cutting paper'],
      ['RULER', 'Measures a straight line'],
      ['ERASER', 'Rubs out mistakes'],
      ['PROJECT', 'Longer piece of work'],
      ['ASSEMBLY', 'Whole school gathering'],
      ['UNIFORM', 'Worn by every pupil'],
      ['ALPHABET', 'A to Z'],
      ['NUMBER', 'Used for counting'],
      ['LESSON', 'One period of teaching'],
      ['REPORT', 'Says how you are doing'],
      ['CHALK', 'Used on a blackboard'],
      ['GLOBE', 'Round model of the earth'],
      ['NOTEBOOK', 'Where notes are written'],
      ['SATCHEL', 'Bag for carrying books'],
      ['RECESS', 'Break between lessons'],
    ]),
  },
  {
    id: 'music',
    name: 'Music',
    audience: 'general',
    words: mk([
      ['ORCHESTRA', 'Large group of players'],
      ['CLARINET', 'Woodwind with a reed'],
      ['TRUMPET', 'Brass with three valves'],
      ['MELODY', 'The tune you hum'],
      ['HARMONY', 'Notes sounded together'],
      ['RHYTHM', 'The beat of a piece'],
      ['CHORUS', 'Repeated part of a song'],
      ['SYMPHONY', 'Large work for orchestra'],
      ['COMPOSER', 'Writes the music'],
      ['CONDUCTOR', 'Waves the baton'],
      ['SOPRANO', 'Highest singing voice'],
      ['OCTAVE', 'Eight notes apart'],
      ['ENCORE', 'Played after the applause'],
      ['BALLAD', 'Slow story song'],
      ['ACOUSTIC', 'Not amplified'],
      ['VIOLIN', 'Bowed string instrument'],
      ['PIANO', 'Has 88 keys'],
      ['GUITAR', 'Strummed with six strings'],
      ['TEMPO', 'Speed of the music'],
      ['LYRICS', 'Words of a song'],
      ['CONCERT', 'Live performance'],
      ['STUDIO', 'Where records are made'],
      ['DRUMS', 'Hit with sticks'],
      ['CELLO', 'Large bowed instrument'],
      ['FLUTE', 'Blown across the mouthpiece'],
      ['SCALE', 'Notes in ascending order'],
    ]),
  },
  {
    id: 'science',
    name: 'Science',
    audience: 'adult',
    words: mk([
      ['GRAVITY', 'Pulls things down'],
      ['MOLECULE', 'Group of bonded atoms'],
      ['CIRCUIT', 'Path for electric current'],
      ['NEUTRON', 'Uncharged particle'],
      ['ENZYME', 'Biological catalyst'],
      ['ORBIT', 'Path around a planet'],
      ['FOSSIL', 'Preserved ancient remains'],
      ['MAGNET', 'Attracts iron'],
      ['PRESSURE', 'Force over an area'],
      ['ELEMENT', 'Entry on the periodic table'],
      ['VOLTAGE', 'Electrical potential difference'],
      ['SPECTRUM', 'Band of split light'],
      ['GENOME', 'Complete set of genes'],
      ['PROTON', 'Positive nuclear particle'],
      ['CRYSTAL', 'Regular solid lattice'],
      ['FRICTION', 'Resists sliding'],
      ['NUCLEUS', 'Centre of an atom'],
      ['SOLVENT', 'Does the dissolving'],
      ['GALAXY', 'Vast system of stars'],
      ['MASS', 'Amount of matter'],
      ['ENERGY', 'Capacity to do work'],
      ['CARBON', 'Element in all life'],
      ['LASER', 'Focused beam of light'],
      ['PLASMA', 'Fourth state of matter'],
      ['THEORY', 'Well-tested explanation'],
      ['ISOTOPE', 'Same element, different mass'],
    ]),
  },
  {
    id: 'garden',
    name: 'Garden',
    audience: 'general',
    words: mk([
      ['COMPOST', 'Rotted garden waste'],
      ['SEEDLING', 'Very young plant'],
      ['TRELLIS', 'Frame for climbers'],
      ['PRUNING', 'Cutting back growth'],
      ['LAVENDER', 'Fragrant purple herb'],
      ['SUNFLOWER', 'Tall yellow-headed bloom'],
      ['MARIGOLD', 'Bright orange bedding flower'],
      ['GREENHOUSE', 'Glass growing house'],
      ['TULIP', 'Cup-shaped spring bulb'],
      ['DAFFODIL', 'Yellow trumpet flower'],
      ['HEDGE', 'Living green boundary'],
      ['MULCH', 'Spread to hold moisture'],
      ['SPROUT', 'Begin to grow'],
      ['ORCHARD', 'Where fruit trees grow'],
      ['THORN', 'Sharp point on a rose'],
      ['PETAL', 'Coloured part of a flower'],
      ['ROOTS', 'Below the soil'],
      ['SHOVEL', 'Digging tool'],
      ['WHEELBARROW', 'One-wheeled carrier'],
      ['NECTAR', 'Sweet draw for bees'],
      ['POLLEN', 'Carried between flowers'],
      ['BULB', 'Planted in autumn'],
      ['FERN', 'Shade-loving frond plant'],
      ['MOSS', 'Soft green carpet plant'],
      ['VINE', 'Climbing stem'],
      ['SHRUB', 'Small woody plant'],
    ]),
  },
];

